### ISSUE TITLE
Light temperature is always going to default (coolest) value

### ISSUE THREAD

**Issue by iiEviNii** [lkempf/casambi-bt-hass#59] opened 2023-12-22 00:25 UTC
**Describe the bug**
Regardless of what light temperature I move the slider to, it always goes to the maximum (ie. coolest) temperature.
There's a second (related) bug, where changing the brightness, regardless of the temperature, causes the temperature to go to its coolest value even though only the brightness should be changed.

My theory is that the packet build is having an issue, causing the light to just revert to "default" brightness, ie. the coolest value.

**To Reproduce**
Open light in HAOS dashboard
Change to "temperature" mode.
Make temperature warmer.
(For second bug; change temperature to warmer than default, then change brightness)

**Expected behavior**
Temperature should be customisable.

**Versions**
HA: 2024.1.0.dev20231218 (Raspberry Pi 5 dev build)
Integration: v0.0.7

**Logs**
In below logs, light temperature was set to minimum (2700K) in Casambi app. Home Assistant integration was used to set to highest (6450K), then back to lowest.
```
2023-12-22 00:08:36.566 DEBUG (MainThread) [CasambiBt._unit] Packing [(0, 8, 4), (8, 8, 255)] as bytearray(b'\x04\xff')
2023-12-22 00:08:36.566 DEBUG (MainThread) [CasambiBt._casambi] Sending operation SetState with payload b'04ff' for 201
2023-12-22 00:08:36.566 DEBUG (MainThread) [CasambiBt._client] Sending packet b'28023000170201000004ff' with counter 24
2023-12-22 00:08:36.566 DEBUG (MainThread) [CasambiBt._client] Packet with header: b'180000000728023000170201000004ff'
2023-12-22 00:08:36.566 INFO (MainThread) [CasambiBt._encryption] Encrypting packet: b'180000000728023000170201000004ff' of len 16 with nonce b'7b9105c91800000080b585177ed84e44'
2023-12-22 00:08:36.567 DEBUG (MainThread) [CasambiBt._encryption] Encrypted packet: b'18000000891c92b0a3bc9aff06587ed9'
2023-12-22 00:08:36.568 DEBUG (MainThread) [CasambiBt._encryption] Authenticated packet: b'18000000891c92b0a3bc9aff06587ed9cb5e082156af5cabe2c5e6f5ea656b01'
2023-12-22 00:08:36.647 DEBUG (MainThread) [CasambiBt._client] Callback on handle c9ffde48-ca5a-0001-ab83-8f519b482f77 (Handle: 8): Unknown: b'3500008033f0c71e18ce4a5298f1a89192f3318e0b080329427b101f'
2023-12-22 00:08:36.647 INFO (MainThread) [CasambiBt._encryption] Decrypting packet: b'3500008033f0c71e18ce4a5298f1a89192f3318e0b080329427b101f' of len 28 with nonce b'35000080a696643380b585177ed84e44'
2023-12-22 00:08:36.648 DEBUG (MainThread) [CasambiBt._encryption] Decrypted package: b'06021713800404ff'
2023-12-22 00:08:36.649 DEBUG (MainThread) [CasambiBt._client] Incoming data of type 6: b'06021713800404ff'
2023-12-22 00:08:36.649 INFO (MainThread) [CasambiBt._client] Parsing incoming unit states...
2023-12-22 00:08:36.649 DEBUG (MainThread) [CasambiBt._client] Incoming unit state: b'021713800404ff'
2023-12-22 00:08:36.649 DEBUG (MainThread) [CasambiBt._client] Parsed state: Id 2, prio 3, online True, on True, state b'04ff'1
2023-12-22 00:08:36.649 INFO (MainThread) [CasambiBt._casambi] Incomming data callback of type 6
2023-12-22 00:08:36.649 DEBUG (MainThread) [CasambiBt._casambi] Handling changed state b'04ff' for unit 2
2023-12-22 00:08:36.649 DEBUG (MainThread) [CasambiBt._unit] Parsed b'04ff' to UnitState(dimmer=4, vertical=None, rgb=None, white=None, temperature=6500)
2023-12-22 00:08:36.649 DEBUG (MainThread) [custom_components.casambi_bt.light] Handling state change for unit 2
2023-12-22 00:08:37.159 DEBUG (MainThread) [CasambiBt._unit] Packing [(0, 8, 4), (8, 8, 255)] as bytearray(b'\x04\xff')
2023-12-22 00:08:37.159 DEBUG (MainThread) [CasambiBt._casambi] Sending operation SetState with payload b'04ff' for 201
2023-12-22 00:08:37.159 DEBUG (MainThread) [CasambiBt._client] Sending packet b'28023000180201000004ff' with counter 25
2023-12-22 00:08:37.159 DEBUG (MainThread) [CasambiBt._client] Packet with header: b'190000000728023000180201000004ff'
2023-12-22 00:08:37.159 INFO (MainThread) [CasambiBt._encryption] Encrypting packet: b'190000000728023000180201000004ff' of len 16 with nonce b'7b9105c91900000080b585177ed84e44'
2023-12-22 00:08:37.161 DEBUG (MainThread) [CasambiBt._encryption] Encrypted packet: b'1900000076ce50216d8c41101b199489'
2023-12-22 00:08:37.161 DEBUG (MainThread) [CasambiBt._encryption] Authenticated packet: b'1900000076ce50216d8c41101b19948970115486858fd39ac585aab0d0c86654'
2023-12-22 00:08:37.340 INFO (MainThread) [universal_silabs_flasher.flasher] Probing ApplicationType.CPC at 230400 baud
2023-12-22 00:08:41.648 INFO (MainThread) [universal_silabs_flasher.flasher] Probing ApplicationType.EZSP at 115200 baud
2023-12-22 00:08:42.897 INFO (MainThread) [universal_silabs_flasher.flasher] Detected ApplicationType.EZSP, version '6.10.3.0 build 297' (6.10.3.0.297) at 115200 baudrate (bootloader baudrate None)
2023-12-22 00:08:43.343 DEBUG (MainThread) [CasambiBt._unit] Packing [(0, 8, 4), (8, 8, 255)] as bytearray(b'\x04\xff')
2023-12-22 00:08:43.343 DEBUG (MainThread) [CasambiBt._casambi] Sending operation SetState with payload b'04ff' for 201
2023-12-22 00:08:43.343 DEBUG (MainThread) [CasambiBt._client] Sending packet b'28023000190201000004ff' with counter 26
2023-12-22 00:08:43.343 DEBUG (MainThread) [CasambiBt._client] Packet with header: b'1a0000000728023000190201000004ff'
2023-12-22 00:08:43.343 INFO (MainThread) [CasambiBt._encryption] Encrypting packet: b'1a0000000728023000190201000004ff' of len 16 with nonce b'7b9105c91a00000080b585177ed84e44'
2023-12-22 00:08:43.344 DEBUG (MainThread) [CasambiBt._encryption] Encrypted packet: b'1a0000005264b54617cd6be289e032ae'
2023-12-22 00:08:43.344 DEBUG (MainThread) [CasambiBt._encryption] Authenticated packet: b'1a0000005264b54617cd6be289e032ae99ef676e41afe2628af1971474271f7a'
2023-12-22 00:08:43.885 DEBUG (MainThread) [CasambiBt._unit] Packing [(0, 8, 4), (8, 8, 255)] as bytearray(b'\x04\xff')
2023-12-22 00:08:43.885 DEBUG (MainThread) [CasambiBt._casambi] Sending operation SetState with payload b'04ff' for 201
2023-12-22 00:08:43.885 DEBUG (MainThread) [CasambiBt._client] Sending packet b'280230001a0201000004ff' with counter 27
2023-12-22 00:08:43.885 DEBUG (MainThread) [CasambiBt._client] Packet with header: b'1b00000007280230001a0201000004ff'
2023-12-22 00:08:43.885 INFO (MainThread) [CasambiBt._encryption] Encrypting packet: b'1b00000007280230001a0201000004ff' of len 16 with nonce b'7b9105c91b00000080b585177ed84e44'
2023-12-22 00:08:43.892 DEBUG (MainThread) [CasambiBt._encryption] Encrypted packet: b'1b000000e7fc0daf09f8ef538cc641ae'
2023-12-22 00:08:43.892 DEBUG (MainThread) [CasambiBt._encryption] Authenticated packet: b'1b000000e7fc0daf09f8ef538cc641aebe6cddb20479a4234ab127493562e370'
```

**Comment by lkempf** [comment] 2023-12-22 11:49
I'm guessing this is a duplicate of #41 (that issue is partially in German). It should be fixed in casambi-bt but not released yet. I'm planning to get this done tomorrow, so please reopen if 0.0.8 doesn't fix it

**Closed by lkempf** 2023-12-22 11:49 UTC
Labels: bug
